# Generated by Django 3.2.5 on 2021-07-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvsystem',
            name='bom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
