# Generated by Django 3.2.5 on 2021-07-30 05:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pvsystem_bom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('date_detected', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_occurred', models.DateField(blank=True, null=True)),
                ('is_fault', models.BooleanField(default=False)),
                ('fault_type', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('device', models.CharField(blank=True, max_length=128, null=True)),
                ('pvsystem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.pvsystem')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'ordering': ['-date_detected'],
            },
        ),
    ]
